apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pumpkin-be-tls
  namespace: pumpkin-be
spec:
   secretName: pumpkin-be-tls
   issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
   dnsNames:
     - pumpkin-k8s-api.dryink.space

