apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumpkin-be
  labels:
    app: pumpkin-be
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pumpkin-be
  template:
    metadata:
      labels:
        app: pumpkin-be
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: pumpkin-be
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: pumpkin-secret
