apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumpkin-be
  namespace: pumpkin-be
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pumpkin-be
  template:
    metadata:
      labels:
        app: pumpkin-be
    spec:
      containers:
        - name: pumpkin-be
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"  #it mean you are giving 0.1 CPU core coz 1000m = 1 CPU core
              memory: "256Mi" # it means 1 Mi (mebibytes) = 1.05 MB it means 256Mi = 256MB of RAM
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: pumpkin-secret
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          secret:
            secretName: pumpkin-secret
            items:
              - key: .env
                path: .env

