apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pumpkin-ingress
  namespace: pumpkin-be
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pumpkin-k8s-api.dryink.space
      secretName: pumpkin-tls
  rules:
    - host: pumpkin-k8s-api.dryink.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pumpkin-be-service
                port:
                  number: 80
