apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumpkin-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pumpkin-be
  template:
    metadata:
      labels:
        app: pumpkin-be
    spec:
      containers:
        - name: pumpkin-be
          image: yourdocker/pumpkin-be:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: pumpkin-secret
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          secret:
            secretName: pumpkin-secret
            items:
              - key: .env
                path: .env
