replicaCount: 2

image:
  repository: elvishishaan/pumpkin-fe
  tag: "1c5d59d48d2f0d519e29bb3b8233b52690823038"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: pumpkin-k8s.dryink.space
  path: /
  pathType: Prefix

secret:
  enabled: true
  envFileBase64: ""
