replicaCount: 2

image:
  repository: elvishishaan/pumpkin-fe
  tag: 0e34ebb11403331843a2dad80144304d91c90226
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: pumpkin.dryink.space
  path: /
  pathType: Prefix

secret:
  enabled: true
  envFileBase64: ""
