replicaCount: 2

image:
  repository: elvishishaan/pumpkin-fe
  tag: "0be3a1f95350d92ebb8daefe3f6f6c0f2fa5962f"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: pumpkin-k8s.dryink.space
  path: /
  pathType: Prefix

secret:
  enabled: true
  envFileBase64: ""
