replicaCount: 2

image:
  repository: elvishishaan/pumpkin-fe
  tag: "22fd3a81a33a89ae93a007b54f581dad4512689c"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: pumpkin-k8s.dryink.space
  path: /
  pathType: Prefix

secret:
  enabled: true
  envFileBase64: ""
