replicaCount: 2

image:
  repository: elvishishaan/pumpkin-be
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: pumpkin.dryink.space
  path: /
  pathType: Prefix

secret:
  enabled: true
  envFileBase64: ""  # <-- put base64 of your .env here
