apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pumpkin-fe-tls
  namespace: pumpkin-fe
spec:
   secretName: pumpkin-fe-tls
   issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
   dnsNames:
     - pumpkin-k8s-fe.dryink.space

