apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumpkin-fe
  namespace: pumpkin-fe
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pumpkin-fe
  template:
    metadata:
      labels:
        app: pumpkin-fe
    spec:
      containers:
        - name: pumpkin-fe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: pumpkin-fe-secret
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          secret:
            secretName: pumpkin-fe-secret
            items:
              - key: .env
                path: .env

